using SmallWorld.src.Interfaces;
using SmallWorld.src.Model;
using SmallWorld.src.Model.Map;
using SmallWorld.src.Model.Terreno;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SmallWorld.src.Controllers
{
    internal class MapController
    {

        private readonly static MapController MapsController = new MapController();

        private readonly List<ITerrain> Terrains = new List<ITerrain>();

        //TODO: Resolver cómo crear un mapa con terrenos aleatorios y colocar entidades en ellos
        private Map AutoGeneratedMap;

        private MapController() { }
        public static MapController GetController()
        {
            return MapsController;
        }


        private void GenerateMap()
        {
            Terrains.Add(new Air());
            Terrains.Add(new Water());
            Terrains.Add(new Earth());
            AutoGeneratedMap = new Map(Terrains);
        }
    }
}
